<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="DESKTOP-GLRLHRK" name="test.scanario.DemoTest" tests="7" failures="1" timestamp="12 Oct 2020 11:06:37 GMT" time="93.316" errors="0">
  <testcase name="varifyLoginPageUrl" time="19.180" classname="test.scanario.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]">
      <![CDATA[java.lang.AssertionError: expected [http://103.206.163.20:9097/mandiri/do/] but found [http://103.206.163.20:9097/mandiri/do/login]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at test.scanario.DemoTest.varifyLoginPageUrl(DemoTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- varifyLoginPageUrl -->
  <testcase name="varifyLoginPageUrl" time="8.671" classname="test.scanario.DemoTest">
    <skipped/>
  </testcase> <!-- varifyLoginPageUrl -->
  <testcase name="varifyLoginPageUrl" time="23.724" classname="test.scanario.DemoTest">
    <skipped/>
  </testcase> <!-- varifyLoginPageUrl -->
  <testcase name="varifyLoginPageUrl" time="9.367" classname="test.scanario.DemoTest">
    <skipped/>
  </testcase> <!-- varifyLoginPageUrl -->
  <testcase name="varifyLoginPagetitle" time="8.798" classname="test.scanario.DemoTest"/>
  <testcase name="varifyLoginPagetitle" time="13.350" classname="test.scanario.DemoTest">
    <skipped/>
  </testcase> <!-- varifyLoginPagetitle -->
  <testcase name="varifyLoginPageLogo" time="10.226" classname="test.scanario.DemoTest"/>
</testsuite> <!-- test.scanario.DemoTest -->
